"use client";

import {useCallback,useEffect,useState} from "react";

type Doc={id:number;team_id:number;document_type:string;original_filename:string;content_type:string;size_bytes:number;status:string;uploaded_at:string};
type ReviewTeam={id:number;team_name:string;category:string;contact_name:string;email:string;phone:string;pitch_address:string;state_id:number;lga_id:number;review_submitted_at:string};
const labels:Record<string,string>={REGISTRATION:"Registration document",TEAM_ID:"Team identification",OWNER_ID:"Owner identification",OTHER:"Other document"};

export default function AdminVerificationPage(){
 const[docs,setDocs]=useState<Doc[]>([]),[teams,setTeams]=useState<ReviewTeam[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[success,setSuccess]=useState(""),[busy,setBusy]=useState<string|null>(null),[docReason,setDocReason]=useState<Record<number,string>>({}),[teamReason,setTeamReason]=useState<Record<number,string>>({});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const[dr,tr]=await Promise.all([fetch("/api/admin/verification/documents",{cache:"no-store"}),fetch("/api/admin/teams/pending-review",{cache:"no-store"})]);if(dr.status===401||tr.status===401){window.location.replace("/admin/login");return}const[dd,td]=await Promise.all([dr.json(),tr.json()]);if(!dr.ok)throw new Error(dd.error||"Unable to load pending documents");if(!tr.ok)throw new Error(td.error||"Unable to load final team reviews");setDocs(Array.isArray(dd)?dd:[]);setTeams(Array.isArray(td)?td:[])}catch(e){setError(e instanceof Error?e.message:"Unable to load admin review queues")}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 async function logout(){await fetch("/api/admin/session",{method:"DELETE"});window.location.replace("/admin/login")}
 async function reviewDoc(id:number,action:"approve"|"reject"){if(action==="reject"&&!docReason[id]?.trim()){setError("Enter a rejection reason before rejecting a document.");return}setBusy(`doc-${id}`);setError("");setSuccess("");try{const r=await fetch(`/api/admin/verification/documents/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({document_id:id,rejection_reason:docReason[id]?.trim()})});const data=await r.json();if(r.status===401){window.location.replace("/admin/login");return}if(!r.ok)throw new Error(data.error||`Unable to ${action} document`);setDocs(v=>v.filter(d=>d.id!==id));setSuccess(`Document ${action==="approve"?"approved":"rejected"} successfully.`)}catch(e){setError(e instanceof Error?e.message:"Document review failed")}finally{setBusy(null)}}
 async function reviewTeam(id:number,action:"approve"|"reject"){const reason=teamReason[id]?.trim()||"";if(action==="reject"&&!reason){setError("Enter a rejection reason before rejecting a team.");return}setBusy(`team-${id}`);setError("");setSuccess("");try{const r=await fetch(`/api/admin/teams/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({team_id:id,reason})});const data=await r.json();if(r.status===401){window.location.replace("/admin/login");return}if(!r.ok)throw new Error(data.error||`Unable to ${action} team`);setTeams(v=>v.filter(t=>t.id!==id));setSuccess(action==="approve"?"Team verified successfully. Verification is valid for one year.":"Team rejected. The resubmission window is now active.")}catch(e){setError(e instanceof Error?e.message:"Final team review failed")}finally{setBusy(null)}}
 return <main className="adminReviewPage"><section className="adminReviewShell"><header><div><span className="formKicker">ADMIN · VERIFICATION</span><h1>Verification review</h1><p>Review identity documents, then make the final decision for teams that completed payment and submitted for review.</p></div><div className="adminHeaderActions"><button className="ghostButton" onClick={load} disabled={loading}>Refresh</button><button className="logoutButton" onClick={logout}>Log out</button></div></header>{error&&<p className="formError">{error}</p>}{success&&<p className="formSuccess">{success}</p>}

 <div className="matchTabs"><b>Final team review</b><span>{teams.length} waiting</span></div>
 {loading?<div className="adminEmpty">Loading final team reviews…</div>:teams.length===0?<div className="adminEmpty"><h2>No teams awaiting final review</h2><p>Teams appear here after approved documents, successful payment, and review submission.</p></div>:<div className="adminDocGrid">{teams.map(t=><article className="adminDocCard" key={t.id}><div className="adminDocTop"><div><span className="cardLabel">TEAM #{t.id} · {t.category}</span><h2>{t.team_name}</h2><p>{t.pitch_address}</p></div><span className="adminPending">FINAL REVIEW</span></div><dl><div><dt>Contact</dt><dd>{t.contact_name} · {t.phone}</dd></div><div><dt>Email</dt><dd>{t.email}</dd></div><div><dt>Location IDs</dt><dd>State {t.state_id} · LGA {t.lga_id}</dd></div><div><dt>Submitted</dt><dd>{new Date(t.review_submitted_at).toLocaleString()}</dd></div></dl><label className="adminReason">Final rejection reason<textarea value={teamReason[t.id]||""} onChange={e=>setTeamReason(v=>({...v,[t.id]:e.target.value}))} placeholder="Required only when rejecting the team"/></label><div className="adminActions"><button onClick={()=>reviewTeam(t.id,"reject")} disabled={busy===`team-${t.id}`} className="adminReject">Reject team</button><button onClick={()=>reviewTeam(t.id,"approve")} disabled={busy===`team-${t.id}`} className="button">{busy===`team-${t.id}`?"Working…":"Verify team"}</button></div></article>)}</div>}

 <div className="matchTabs"><b>Document review</b><span>{docs.length} pending</span></div>
 {loading?<div className="adminEmpty">Loading pending documents…</div>:docs.length===0?<div className="adminEmpty"><h2>Document queue is clear</h2><p>There are no pending verification documents.</p></div>:<div className="adminDocGrid">{docs.map(d=><article className="adminDocCard" key={d.id}><div className="adminDocTop"><div><span className="cardLabel">TEAM #{d.team_id}</span><h2>{labels[d.document_type]||d.document_type}</h2><p>{d.original_filename}</p></div><span className="adminPending">PENDING</span></div><dl><div><dt>Uploaded</dt><dd>{new Date(d.uploaded_at).toLocaleString()}</dd></div><div><dt>File</dt><dd>{Math.max(1,Math.round(d.size_bytes/1024))} KB · {d.content_type}</dd></div></dl><a className="ghostButton adminView" href={`/api/admin/verification/documents/view?document_id=${d.id}`} target="_blank" rel="noreferrer">View private document</a><label className="adminReason">Rejection reason<textarea value={docReason[d.id]||""} onChange={e=>setDocReason(v=>({...v,[d.id]:e.target.value}))} placeholder="Required only when rejecting"/></label><div className="adminActions"><button onClick={()=>reviewDoc(d.id,"reject")} disabled={busy===`doc-${d.id}`} className="adminReject">Reject</button><button onClick={()=>reviewDoc(d.id,"approve")} disabled={busy===`doc-${d.id}`} className="button">{busy===`doc-${d.id}`?"Working…":"Approve"}</button></div></article>)}</div>}</section></main>
}