"use client";

import {useCallback,useEffect,useState} from "react";

type Doc={id:number;team_id:number;document_type:string;original_filename:string;content_type:string;size_bytes:number;status:string;uploaded_at:string};
const labels:Record<string,string>={REGISTRATION:"Registration document",TEAM_ID:"Team identification",OWNER_ID:"Owner identification",OTHER:"Other document"};

export default function AdminVerificationPage(){
 const [docs,setDocs]=useState<Doc[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState<number|null>(null),[reason,setReason]=useState<Record<number,string>>({});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/admin/verification/documents",{cache:"no-store"});const data=await r.json();if(!r.ok)throw new Error(data.error||"Unable to load pending documents");setDocs(data)}catch(e){setError(e instanceof Error?e.message:"Unable to load pending documents")}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 async function review(id:number,action:"approve"|"reject"){if(action==="reject"&&!reason[id]?.trim()){setError("Enter a rejection reason before rejecting a document.");return}setBusy(id);setError("");try{const r=await fetch(`/api/admin/verification/documents/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({document_id:id,rejection_reason:reason[id]?.trim()})});const data=await r.json();if(!r.ok)throw new Error(data.error||`Unable to ${action} document`);setDocs(v=>v.filter(d=>d.id!==id))}catch(e){setError(e instanceof Error?e.message:"Review failed")}finally{setBusy(null)}}
 return <main className="adminReviewPage"><section className="adminReviewShell"><header><div><span className="formKicker">ADMIN · VERIFICATION</span><h1>Document review</h1><p>Review private team documents before approval. Pending documents are shown oldest first.</p></div><button className="ghostButton" onClick={load} disabled={loading}>Refresh</button></header>{error&&<p className="formError">{error}</p>}{loading?<div className="adminEmpty">Loading pending documents…</div>:docs.length===0?<div className="adminEmpty"><h2>Review queue is clear</h2><p>There are no pending verification documents.</p></div>:<div className="adminDocGrid">{docs.map(d=><article className="adminDocCard" key={d.id}><div className="adminDocTop"><div><span className="cardLabel">TEAM #{d.team_id}</span><h2>{labels[d.document_type]||d.document_type}</h2><p>{d.original_filename}</p></div><span className="adminPending">PENDING</span></div><dl><div><dt>Uploaded</dt><dd>{new Date(d.uploaded_at).toLocaleString()}</dd></div><div><dt>File</dt><dd>{Math.max(1,Math.round(d.size_bytes/1024))} KB · {d.content_type}</dd></div></dl><a className="ghostButton adminView" href={`/api/admin/verification/documents/view?document_id=${d.id}`} target="_blank" rel="noreferrer">View private document</a><label className="adminReason">Rejection reason<textarea value={reason[d.id]||""} onChange={e=>setReason(v=>({...v,[d.id]:e.target.value}))} placeholder="Required only when rejecting"/></label><div className="adminActions"><button onClick={()=>review(d.id,"reject")} disabled={busy===d.id} className="adminReject">Reject</button><button onClick={()=>review(d.id,"approve")} disabled={busy===d.id} className="button">{busy===d.id?"Working…":"Approve"}</button></div></article>)}</div>}</section></main>
}